# Configuration for Testy mc testerson Website
# This file is used by the custom CMS system
repository: prairiegiraffe/testy-mc-testerson
branch: main
site_name: Testy mc testerson
generated_at: 2025-08-20T21:37:31.167Z